export default [
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "MW",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "0.20",
         "unitCost": "$ 60.00",
         "cost": "$ 12.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "ACDC",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "5.60",
         "unitCost": "$ 60.00",
         "cost": "$ 336.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "ACDC/LemD",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "1.30",
         "unitCost": "$ 60.00",
         "cost": "$ 78.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "MW/DHDS",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "1.50",
         "unitCost": "$ 60.00",
         "cost": "$ 90.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "GG4",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 15.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "DD",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 15.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Cheese",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 15.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "CW/LemD",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 15.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "CW/ACDC",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "0.10",
         "unitCost": "$ 60.00",
         "cost": "$ 6.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "CBG",
         "prodX": "",
         "unitMeas": "seeds",
         "unitNow": "50.00",
         "unitCost": "$ 15.00",
         "cost": "$ 750.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "DE",
         "prodX": "",
         "unitMeas": "1 bag",
         "unitNow": "1.00",
         "unitCost": "$ 20.00",
         "cost": "$ 20.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Living Acres",
         "prodX": "",
         "unitMeas": "1 bag",
         "unitNow": "4.00",
         "unitCost": "$ 11.00",
         "cost": "$ 44.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Perlite",
         "prodX": "",
         "unitMeas": "1 bag",
         "unitNow": "4.00",
         "unitCost": "$ 42.70",
         "cost": "$ 170.80",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Compost",
         "prodX": "",
         "unitMeas": "1yard",
         "unitNow": "1.00",
         "unitCost": "$ 38.00",
         "cost": "$ 38.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Surf/Turf",
         "prodX": "",
         "unitMeas": "1 yard",
         "unitNow": "1.00",
         "unitCost": "$ 45.00",
         "cost": "$ 45.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Peat Moss",
         "prodX": "",
         "unitMeas": "1 bag",
         "unitNow": "1.00",
         "unitCost": "$ 16.99",
         "cost": "$ 16.99",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "D. Earth",
         "prodX": "",
         "unitMeas": "1 bag",
         "unitNow": "1.00",
         "unitCost": "$ 20.00",
         "cost": "$ 20.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Coconut Coir",
         "prodX": "",
         "unitMeas": "1 bag",
         "unitNow": "1.00",
         "unitCost": "$ 0.09",
         "cost": "$ 0.09",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Bloom",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "102.00",
         "unitCost": "$ 0.25",
         "cost": "$ 25.50",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Sugerfree",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.51",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Micro",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "128.00",
         "unitCost": "$ 0.23",
         "cost": "$ 29.44",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Uncle John",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.80",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Jacks A",
         "prodX": "",
         "unitMeas": "grams",
         "unitNow": "  6,795.00 ",
         "unitCost": "$ 0.01",
         "cost": "$ 33.98",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Magnesium",
         "prodX": "",
         "unitMeas": "grams",
         "unitNow": "  6,795.00 ",
         "unitCost": "$ 0.002",
         "cost": "$ 13.59",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Jacks bloom",
         "prodX": "",
         "unitMeas": "grams",
         "unitNow": "  11,325.00 ",
         "unitCost": "$ 0.01",
         "cost": "$ 56.63",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Nuke",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.03",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Jacks B",
         "prodX": "",
         "unitMeas": "grams",
         "unitNow": "  6,795.00 ",
         "unitCost": "$ 0.003",
         "cost": "$ 20.39",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Komplete Lite",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "pods",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 1.08",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "6” pots",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 1.40",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "1 gal pot",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "125.00",
         "unitCost": "$ 1.80",
         "cost": "$ 225.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "5 gallon pots",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 1.60",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "15 gal cloth",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "35.00",
         "unitCost": "$ 7.25",
         "cost": "$ 253.75",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "25 gal cloth",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "55.00",
         "unitCost": "$ 8.35",
         "cost": "$ 459.25",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "40 gal",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "4.00",
         "unitCost": "$ 11.17",
         "cost": "$ 44.68",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "lights Bulbs",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 11.95",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Plant Markers",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Super Sprouter",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "$ 15.05",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "lady bugs",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Clonex",
         "prodX": "",
         "unitMeas": "bottle",
         "unitNow": "",
         "unitCost": "$ 25.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Big packs",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "",
         "unitCost": "$ 5.46",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Supplies Plant Growth",
         "prodInventoryName": "Supplies Plant Growth",
         "detail": "Small packs",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "R4",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "48.99",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "ACDC",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "39.40",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "MW",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "14.50",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "DD",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "MW/DHDS",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "LemD",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "104.66",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "Sativa",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Processing Flower",
         "detail": "Indica",
         "prodX": "",
         "unitMeas": "Oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "ACDC/CW",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "33.90",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "CW",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "0.70",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "Sts",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "1.06",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "ACDC",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "1.60",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "CBG",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "17.10",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "MW  Indica",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "GG4 sativa",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "7.80",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "Sativa",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "Indica",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "CBN",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "2.10",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "Dry Ice",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil/ RSO",
         "detail": "CBD distillate",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "No 10 Avocado",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Wound",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Crisis Management",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "THC/CBD olive oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "4.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "chaga Glycerin",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "40.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Pain",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "24.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Throat Coat",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "32.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Anti Age Avocado",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "40.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Massage Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "128.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Night & Body",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "240.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Holy Basil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Rice Bran Dark spots",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Rice Bran W CBD",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Infused Coconut oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Witchhazel hydrosol",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Custom In House Oils",
         "detail": "Infused Glycerin",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Green Apple",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "$ 7.60",
         "cost": "$ 15.20",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "marshmallow",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "20.00",
         "unitCost": "$ 1.30",
         "cost": "$ 26.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Cranberry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 4.98",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Fruit Punch",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "1.00",
         "unitCost": "$ 6.50",
         "cost": "$ 6.50",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Hot Chili",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "1.00",
         "unitCost": "$ 6.50",
         "cost": "$ 6.50",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Tuttifrutti",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "4.00",
         "unitCost": "$ 4.98",
         "cost": "$ 19.92",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Eggnog",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "$ 4.98",
         "cost": "$ 9.96",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Grape",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "4.00",
         "unitCost": "$ 5.75",
         "cost": "$ 23.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "peach",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "6.00",
         "unitCost": "$ 5.75",
         "cost": "$ 34.50",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Strawberrry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "4.00",
         "unitCost": "$ 5.75",
         "cost": "$ 23.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Cherry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 1.89",
         "cost": "$ 15.12",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Tangerine",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "$ 4.98",
         "cost": "$ 9.96",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Tart & Sour",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "28.00",
         "unitCost": "$ 5.75",
         "cost": "$ 161.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Mango",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "10.00",
         "unitCost": "$ 4.98",
         "cost": "$ 49.80",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Blueberry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "20.00",
         "unitCost": "$ 5.75",
         "cost": "$ 115.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Lemongrass",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "12.00",
         "unitCost": "$ 4.98",
         "cost": "$ 59.76",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Frankensense",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 7.75",
         "cost": "$ 62.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Watermelon",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "20.00",
         "unitCost": "$ 1.89",
         "cost": "$ 37.80",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Pineapple",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "10.00",
         "unitCost": "$ 4.98",
         "cost": "$ 49.80",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Raspeberry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.89",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Papaya Juice Powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "$ 1.24",
         "cost": "$ 19.84",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Pineapple Juice Powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "$ 1.24",
         "cost": "$ 19.84",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Flavor enhancer",
         "detail": "Orange",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.89",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Emu",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "5.00",
         "unitCost": "$ 4.75",
         "cost": "$ 23.75",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Safflower",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "96.00",
         "unitCost": "$ 0.93",
         "cost": "$ 89.28",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Avocado",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "128.00",
         "unitCost": "$ 0.49",
         "cost": "$ 62.72",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Vit E",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "2.50",
         "unitCost": "$ 19.97",
         "cost": "$ 49.93",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Coconut Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.38",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Olive Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.35",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Bees Wax",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.55",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Emulsifying Wax",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "28.00",
         "unitCost": "$ 0.53",
         "cost": "$ 14.84",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Cantuaba",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "32.00",
         "unitCost": "$ 1.12",
         "cost": "$ 35.84",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "grapeseed oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.25",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Peg #40",
         "prodX": "",
         "unitMeas": "grams",
         "unitNow": "600.00",
         "unitCost": "$ 0.03",
         "cost": "$ 18.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Abyssinian",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "$ 3.27",
         "cost": "$ 52.32",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "IPM",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "26.00",
         "unitCost": "$ 1.55",
         "cost": "$ 40.30",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Lemon Balm",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Calendula pet jelly",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "27.00",
         "unitCost": "$ 0.37",
         "cost": "$ 9.99",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Frankincense",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "4.00",
         "unitCost": "$ 30.15",
         "cost": "$ 120.60",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Camelina",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 2.49",
         "cost": "$ 19.92",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Passion Fruit",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "15.00",
         "unitCost": "$ 4.24",
         "cost": "$ 63.60",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Shea Butter",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "64.00",
         "unitCost": "$ 1.28",
         "cost": "$ 81.92",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Turkey Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "32.00",
         "unitCost": "$ 0.86",
         "cost": "$ 27.52",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Phenonip",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "90.00",
         "unitCost": "$ 2.58",
         "cost": "$ 232.20",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Apricot oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "64.00",
         "unitCost": "$ 1.24",
         "cost": "$ 79.36",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Rice Bran",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "6.00",
         "unitCost": "$ 0.18",
         "cost": "$ 1.08",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "MCT",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "32.00",
         "unitCost": "$ 1.00",
         "cost": "$ 32.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Cacoa Butter",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 1.12",
         "cost": "$ 8.96",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Hemp",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.54",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Seseme seed",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.52",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Pumpkin oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "castor oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.15",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "Jojoba",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Oil",
         "detail": "tamanu oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Arco Bark",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 3.75",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Calendula  Flowers",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.95",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Graviola",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "White Sage",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 4.50",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Maca",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Milk Thistle",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Seaweed usnea",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.26",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Oregon Grape Root",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 3.25",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Butterfly tea",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 5.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Oregeno",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 3.25",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Thyme",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.99",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Yarrow",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.51",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Wormwood",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 5.52",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Elderberry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.48",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Bladdwrack",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.31",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Chaga",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 5.81",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Horsetail",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.31",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Marshmallow",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.43",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Nettles",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 5.52",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "comfrey",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 5.52",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Red clover",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Burdock",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "Thistle",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "yellowdock",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.12",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "ginger",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "$ 1.99",
         "cost": "$ 31.84",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Herbs",
         "detail": "mullien",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 5.79",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "B-12 Boost",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.53",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Agave",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "42.00",
         "unitCost": "$ 1.00",
         "cost": "$ 42.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Aloe powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 9.36",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Sleep Complete",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.48",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Aloe H2O",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.87",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Witchhazel",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 8.79",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Silver",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 3.74",
         "cost": "$ 29.92",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Potassium Sobate",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "14.00",
         "unitCost": "$ 3.50",
         "cost": "$ 49.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Steric Acid  food grade",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "21.00",
         "unitCost": "$ 1.12",
         "cost": "$ 23.52",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Baking Soda",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "7.75",
         "unitCost": "$ 0.10",
         "cost": "$ 0.78",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Versawhip",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "$ 1.06",
         "cost": "$ 16.96",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "glucose",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 0.34",
         "cost": "$ 2.72",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Lecithan Powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Erythritol",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "240.00",
         "unitCost": "$ 0.26",
         "cost": "$ 62.40",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Everclear",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.62",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Cashew Milk Powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "16.00",
         "unitCost": "$ 1.24",
         "cost": "$ 19.84",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Coconut milk",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.99",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Citric Acid",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 0.39",
         "cost": "$ 3.12",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Coconut Sugar",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "64.00",
         "unitCost": "$ 1.20",
         "cost": "$ 76.80",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Lye",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.87",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Gelatin",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "48.00",
         "unitCost": "$ 0.90",
         "cost": "$ 43.20",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "goats milk",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Glycerin",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "59.00",
         "unitCost": "$ 0.20",
         "cost": "$ 11.80",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "vegan gelatin",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "4.00",
         "unitCost": "$ 1.06",
         "cost": "$ 4.24",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Fruit juice",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "peaches",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.28",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Hyl. Acid",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.43",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Honey",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Stearic Acid",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "6.00",
         "unitCost": "$ 0.37",
         "cost": "$ 2.22",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Bluberries",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "384.00",
         "unitCost": "$ 0.28",
         "cost": "$ 107.52",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Tart Cherry Powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "10.00",
         "unitCost": "$ 1.56",
         "cost": "$ 15.60",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Sleep Complete",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "96.00",
         "unitCost": "$ 1.15",
         "cost": "$ 110.40",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Glucose",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "6.00",
         "unitCost": "$ 0.70",
         "cost": "$ 4.23",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Raw Ingr.",
         "detail": "Whitesugar",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.20",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Calm",
         "detail": "Raspberry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 1.31",
         "cost": "$ 10.48",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Calm",
         "detail": "Cherry",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "8.00",
         "unitCost": "$ 3.00",
         "cost": "$ 24.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Calm",
         "detail": "Watermelon",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "20.00",
         "unitCost": "$ 3.00",
         "cost": "$ 60.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Calm",
         "detail": "Orange",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "6.00",
         "unitCost": "$ 1.54",
         "cost": "$ 9.24",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Essential Oils",
         "detail": "Pink Pepper",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "$ 21.50",
         "cost": "$ 43.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Essential Oils",
         "detail": "Marjoram",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.49",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Essential Oils",
         "detail": "Rose Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.63",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Tissue paper",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "",
         "unitCost": "",
         "cost": "",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Flexible clear tubing 2#",
         "prodX": "",
         "unitMeas": "750 ft",
         "unitNow": "745.00",
         "unitCost": "0.03",
         "cost": "$ 18.87",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Mylar Bags 3x4",
         "prodX": "",
         "unitMeas": "3x4",
         "unitNow": "221.00",
         "unitCost": "$ 0.21",
         "cost": "$ 46.41",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Mylar bags 8x5",
         "prodX": "",
         "unitMeas": "8x5",
         "unitNow": "25.00",
         "unitCost": "$ 0.25",
         "cost": "$ 6.25",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Oxygen Absorbers",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "100.00",
         "unitCost": "$ 0.20",
         "cost": "$ 20.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Basket Wrap",
         "prodX": "",
         "unitMeas": "",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "1 oz Bottles w/dropper",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "53.00",
         "unitCost": "$ 1.80",
         "cost": "$ 95.40",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "8 oz purple",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "19.00",
         "unitCost": "$ 1.92",
         "cost": "$ 36.48",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Pumps",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "14.00",
         "unitCost": "$ 0.62",
         "cost": "$ 8.68",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "1oz with caps",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "1 oz poptubs",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "115.00",
         "unitCost": "$ 0.22",
         "cost": "$ 25.30",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "3 oz poptubs",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "550.00",
         "unitCost": "$ 0.30",
         "cost": "$ 165.00",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "push up TLC small",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "10.00",
         "unitCost": "$ 1.14",
         "cost": "$ 11.40",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "push up TLC large",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "127.00",
         "unitCost": "$ 2.30",
         "cost": "$ 292.10",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Packaging exp. of product",
         "detail": "Face lotion bottles",
         "prodX": "",
         "unitMeas": "each",
         "unitNow": "15.00",
         "unitCost": "$ 2.33",
         "cost": "$ 34.95",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Alfalfa",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ -",
         "cost": "",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Algae Extract",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 3.26",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Aloe Powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "12.00",
         "unitCost": "$ 9.36",
         "cost": "$ 112.32",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Aloe Verra",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.28",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Apricot",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.03",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Avocado Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ -",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Beeswax",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.55",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Benziod gum",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ -",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Burdock Root",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.88",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Camphor Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.81",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Castor",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.79",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Chaparral Leaf",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.50",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Clove Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 13.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Cocao Butter",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.75",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Coconut oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.31",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "E wax",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.35",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Emu",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.02",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Goat’s milk-fresh",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.13",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Goat’s Milk Powder",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.85",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Glycerine",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.53",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "guar gm",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.83",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Hyaleuronic Acid",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.19",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "IPM",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.43",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Jojoba",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.87",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Lanolin",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.24",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Lye",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.25",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Macnt Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.30",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Marjoram Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 8.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Masrshmallow root",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.24",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Meadowfoam",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.03",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Milk Thistle",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.72",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Olive Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.31",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Orange bitters",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 8.50",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Orange Water",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.33",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Oregano Herb",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.13",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Palm Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.31",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Phenoil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.55",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Primrose oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 9.50",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "pumpkin Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.41",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Rhadiola Root",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 3.74",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Rice Bran Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.39",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Rosehip",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.41",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Rosemary Oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 9.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Safflower oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.30",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Sage Herb",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.78",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Sea Kelp",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 3.00",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Sesame Seed oil",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.65",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Shea Nut butter",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ -",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Soap fragrance",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 2.22",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Sodium Borate",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.34",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Thyme herb",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.69",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Vanilla Absolute",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 14.67",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Vetiver",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 31.98",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Vitamin A",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ -",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Wakame",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 1.38",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Willow Bark",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.63",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Wormwood",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 0.78",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Inventory-Product Formulation Supplies",
         "prodInventoryName": "Misc purchases",
         "detail": "Ylang ylang",
         "prodX": "",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "$ 59.96",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "R4",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "ACDC",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "MW",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "DD",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "MW/DHDS",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "LemD",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "Sativa",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "Indica",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "Cotton candy",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "Cheese",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "Lilac diesel",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Raw Flower",
         "detail": "Citral glue",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "-",
         "unitCost": "",
         "cost": "$ -",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Gummies",
         "detail": "Sleep CBG",
         "prodX": "X",
         "unitMeas": "1 oz per pack-packs",
         "unitNow": "12.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Gummies",
         "detail": "Sleep CBD/ACDC",
         "prodX": "X",
         "unitMeas": "1 oz per pack-packs",
         "unitNow": "2.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Gummies",
         "detail": "Sleep Indica",
         "prodX": "X",
         "unitMeas": "1 oz per pack-packs",
         "unitNow": "2.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Gummies",
         "detail": "Lift",
         "prodX": "X",
         "unitMeas": "1 oz per pack-packs",
         "unitNow": "8.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Gummies",
         "detail": "Recovery",
         "prodX": "X",
         "unitMeas": "1 oz per pack-packs",
         "unitNow": "2.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Gummies",
         "detail": "Daytime CBG",
         "prodX": "X",
         "unitMeas": "1 oz per pack-packs",
         "unitNow": "14.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Candies",
         "detail": "CBD/CBN",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "4.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Candies",
         "detail": "Lemongrass",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "34.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Candies",
         "detail": "Watermelon",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "26.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Candies",
         "detail": "Woe",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "34.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Candies",
         "detail": "CBG",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "11.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Tinctures-Base Oil",
         "detail": "Indica glycerin",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Tinctures-Base Oil",
         "detail": "Sativa",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "9.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Tinctures-Base Oil",
         "detail": "Union custom",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "11.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Tinctures-Base Oil",
         "detail": "CBN MCT",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Tinctures-Base Oil",
         "detail": "Chaga",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Garden of Bloom",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Garden of Peace",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "5.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Lip Lover",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "50.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Massage Oil Cream",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "No 10",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Therapeutic Touch",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "2.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Soaps",
         "prodX": "X",
         "unitMeas": "each",
         "unitNow": "12.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "TLC Cream Small",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "22.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "TLC Cream Large",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Bath Balms sm",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "1.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Topicals",
         "detail": "Bath Balms lg",
         "prodX": "X",
         "unitMeas": "oz",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": ""
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Marshmallows",
         "detail": "Indica",
         "prodX": "X",
         "unitMeas": "each",
         "unitNow": "44.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Marshmallows",
         "detail": "Sative",
         "prodX": "X",
         "unitMeas": "each",
         "unitNow": "73.00",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     },
     {
         "class": "Products Available for Sale",
         "prodInventoryName": "Marshmallows",
         "detail": "CBG",
         "prodX": "X",
         "unitMeas": "each",
         "unitNow": "",
         "unitCost": "#REF!",
         "cost": "#REF!",
         "recipes": "R"
     }
 ]